# Generated by Django 5.2 on 2025-11-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefs',
            name='face',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='insta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
