# Generated by Django 5.2 on 2025-11-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_chefs_face_chefs_insta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chefs',
            name='face',
        ),
        migrations.RemoveField(
            model_name='chefs',
            name='insta',
        ),
        migrations.AddField(
            model_name='chefs',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chefs',
            name='instagramm',
            field=models.URLField(blank=True),
        ),
    ]
