# Generated by Django 5.2.8 on 2025-11-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_bbq_menu_bread_menu_fish_menu_kebab_menu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_menu',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
