# Generated by Django 5.2.8 on 2025-11-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_bar_menu_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salad_menu',
            name='description',
        ),
        migrations.AddField(
            model_name='salad_menu',
            name='status',
            field=models.CharField(choices=[('available', 'Mavjud'), ('unavailable', 'Tugagan'), ('preparing', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
    ]
