# Generated by Django 5.2.8 on 2025-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_remove_salad_menu_description_salad_menu_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salad_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
    ]
