# Generated by Django 5.2.8 on 2025-11-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_salad_menu_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionaldishes_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bar_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bbq_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bread_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='burger_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='fish_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='kebab_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='national_dishes_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pizza_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sup_menu',
            name='description',
        ),
        migrations.RemoveField(
            model_name='sweets_menu',
            name='description',
        ),
        migrations.AddField(
            model_name='additionaldishes_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='bar_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='bbq_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='bread_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='burger_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='fish_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='kebab_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='national_dishes_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='pizza_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='sup_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='sweets_menu',
            name='status',
            field=models.CharField(choices=[('Mavjud', 'Mavjud'), ('Tugagan', 'Tugagan'), ('Tayyorlanmoqda', 'Tayyorlanmoqda')], default='available', max_length=20),
        ),
    ]
