# Generated by Django 5.2.8 on 2025-11-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_additionaldishes_menu_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldishes_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/additionaldishes/'),
        ),
        migrations.AlterField(
            model_name='bar_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/bar/'),
        ),
        migrations.AlterField(
            model_name='bbq_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/bbq/'),
        ),
        migrations.AlterField(
            model_name='bread_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/bread/'),
        ),
        migrations.AlterField(
            model_name='burger_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/burger/'),
        ),
        migrations.AlterField(
            model_name='chefs',
            name='image',
            field=models.ImageField(upload_to='media/chefs/'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/comments/'),
        ),
        migrations.AlterField(
            model_name='fish_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/fish/'),
        ),
        migrations.AlterField(
            model_name='kebab_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/kebab/'),
        ),
        migrations.AlterField(
            model_name='national_dishes_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/national/'),
        ),
        migrations.AlterField(
            model_name='parties',
            name='image',
            field=models.ImageField(upload_to='media/parties/'),
        ),
        migrations.AlterField(
            model_name='pizza_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/pizza/'),
        ),
        migrations.AlterField(
            model_name='salad_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/salad/'),
        ),
        migrations.AlterField(
            model_name='sup_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/sup/'),
        ),
        migrations.AlterField(
            model_name='sweets_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/sweets/'),
        ),
    ]
