# Generated by Django 5.2.8 on 2025-11-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_additionaldishes_menu_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_menu',
            name='image',
            field=models.ImageField(upload_to='menu/add/'),
        ),
    ]
