# Generated by Django 5.2.8 on 2025-11-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_bar_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_menu',
            name='image',
            field=models.ImageField(default='img.jpeg', upload_to='menu/add/'),
        ),
    ]
