# Generated by Django 5.2.8 on 2025-11-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_bar_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_menu',
            name='image',
            field=models.ImageField(upload_to='media/menu/adddddddddddd/'),
        ),
    ]
