# Generated by Django 5.2 on 2025-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_alter_bar_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bar_menu',
            name='image',
            field=models.ImageField(upload_to='menu/bar'),
        ),
    ]
